

CREATE TABLE IF NOT EXISTS Gasto (
    id LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
    monto DOUBLE NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    fecha VARCHAR(20),
    descripcion VARCHAR(60)
);
