CREATE TABLE IF NOT EXISTS Gasto (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    descripcion VARCHAR(60),
    monto DOUBLE NOT NULL,
    fecha VARCHAR(20),
    categoria VARCHAR(30) NOT NULL
);
